apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secrets
type: Opaque
stringData:
  db-password: '@<< (datasource "file" "/examples/complete/config/settings.json").secrets.db_password >>@'
  api-key: '@<< (datasource "file" "/examples/complete/config/settings.json").secrets.api_key >>@'
